### ISSUE TITLE
If host on LAN encounters a critical bug everyone is kicked out

### ISSUE THREAD

**Issue by Invictaz** [riperiperi/FreeSO#105]
There is no option that if the host looses connection or is kicked out due to a crashing  bug another user takes over the hosting. Everyones game is stopped now.

**Comment by riperiperi** [comment]
Not a bug, the game does not support switchable hosts since it does not use a P2P model, but rather a client/server. You'd need to use a P2P model and something like ICE to network the systems.

As for sandbox mode, it is currently only intended for use debugging multiplayer objects made with volcanic, or some plugins. A lack of implementation for most of the global link interface means a lot of things will not work.

**Comment by Invictaz** [comment]
@riperiperi there is no other LAN option so I need to use this
